//
//  EditTrainingInteractorTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 17.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

// swiftlint:disable implicitly_unwrapped_optional

final class EditTrainingInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: EditTrainingInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupEditTrainingInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupEditTrainingInteractor() {
        sut = EditTrainingInteractor()
    }
    
    // MARK: Test doubles
    
    final class EditTrainingPresentationLogicSpy: EditTrainingPresentationLogic {
        var presentLoadCalled = false
        
        func presentLoad(response: EditTraining.Load.Response) {
            presentLoadCalled = true
        }
    }
    
    final class EditTrainingRoutingLogicSpy: EditTrainingRoutingLogic {
    }
    
    // MARK: Tests
    
    func testDoLoad() {
        // Given
        let spy = EditTrainingPresentationLogicSpy()
        sut.presenter = spy
        let request = EditTraining.Load.Request()
        
        // When
        sut.doLoad(request: request)
        
        // Then
        XCTAssertTrue(spy.presentLoadCalled, "doLoad(request:) should ask the presenter to format the result")
    }
}
