//
//  SettingsAlertSingleTypeRouter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SettingsAlertSingleTypeRoutingLogic {
    func routeToSound()
}

protocol SettingsAlertSingleTypeDataPassing {
    var dataStore: SettingsAlertSingleTypeDataStore? { get }
}

final class SettingsAlertSingleTypeRouter: NSObject, SettingsAlertSingleTypeRoutingLogic, SettingsAlertSingleTypeDataPassing {
    weak var viewController: SettingsAlertSingleTypeViewController?
    var dataStore: SettingsAlertSingleTypeDataStore?
    
    // MARK: Routing
    func routeToSound() {
        guard let configuration = dataStore?.configuration else { return }
        let soundViewController = SettingsAlertSoundViewController()
        soundViewController.dataStore?.configuration = configuration
        
        present(soundViewController)
    }
    
    private func present(_ viewController: UIViewController) {
        self.viewController?.navigationController?.pushViewController(viewController, animated: true)
    }
}
