//
//  SettingsUserTypeRootPresenter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsUserTypeRootPresentationLogic {
    func presentLoad(response: SettingsUserTypeRoot.Load.Response)
}

final class SettingsUserTypeRootPresenter: SettingsUserTypeRootPresentationLogic {
    weak var viewController: SettingsUserTypeRootDisplayLogic?
    
    // MARK: Do something
    
    func presentLoad(response: SettingsUserTypeRoot.Load.Response) {
        let viewModel = SettingsUserTypeRoot.Load.ViewModel(injectionType: response.injectionType)
        viewController?.displayLoad(viewModel: viewModel)
    }
}
