//
//  SettingsModeFollowerInteractor.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsModeFollowerBusinessLogic {
    func doLoad(request: SettingsModeFollower.Load.Request)
}

protocol SettingsModeFollowerDataStore {
    
}

final class SettingsModeFollowerInteractor: SettingsModeFollowerBusinessLogic, SettingsModeFollowerDataStore {
    var presenter: SettingsModeFollowerPresentationLogic?
    var router: SettingsModeFollowerRoutingLogic?
    
    // MARK: Do something
    
    func doLoad(request: SettingsModeFollower.Load.Request) {
        let response = SettingsModeFollower.Load.Response()
        presenter?.presentLoad(response: response)
    }
}
