//
//  DebugLogRouter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 06.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DebugLogRoutingLogic {
    
}

protocol DebugLogDataPassing {
    var dataStore: DebugLogDataStore? { get }
}

final class DebugLogRouter: NSObject, DebugLogRoutingLogic, DebugLogDataPassing {
    weak var viewController: DebugLogViewController?
    var dataStore: DebugLogDataStore?
    
    // MARK: Routing
    
}
