//
//  DebugLogPresenter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 06.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DebugLogPresentationLogic {
    func presentLoad(response: DebugLog.Load.Response)
    func presentLogs(response: DebugLog.UpdateLog.Response)
}

final class DebugLogPresenter: DebugLogPresentationLogic {
    weak var viewController: DebugLogDisplayLogic?
    
    // MARK: Do something
    
    func presentLoad(response: DebugLog.Load.Response) {
        let viewModel = DebugLog.Load.ViewModel()
        viewController?.displayLoad(viewModel: viewModel)
    }
    
    func presentLogs(response: DebugLog.UpdateLog.Response) {
        let logs = response.logs.joined(separator: "\n")
        let viewModel = DebugLog.UpdateLog.ViewModel(logs: logs)
        viewController?.displayLogs(viewModel: viewModel)
    }
}
