//
//  SettingsUnitsViewControllerTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

final class SettingsUnitsViewControllerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: SettingsUnitsViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupSettingsUnitsViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSettingsUnitsViewController() {
        sut = SettingsUnitsViewController()
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    final class SettingsUnitsBusinessLogicSpy: SettingsUnitsBusinessLogic {
        var doLoadCalled = false
        
        func doLoad(request: SettingsUnits.Load.Request) {
            doLoadCalled = true
        }
    }
    
    // MARK: Tests
    
    func testShouldDoLoadWhenViewIsLoaded() {
        // Given
        let spy = SettingsUnitsBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        
        // Then
        XCTAssertTrue(spy.doLoadCalled, "viewDidLoad() should ask the interactor to do load")
    }
    
    func testDisplayLoad() {
        // Given
        let viewModel = SettingsUnits.Load.ViewModel(tableViewModel: BaseSettings.ViewModel(sections: []))
        
        // When
        loadView()
        
        sut.displayLoad(viewModel: viewModel)
        
        // Then
    }
    
    func testDidSelect() {
        loadView()
        
        guard let tableView = sut.view.subviews.compactMap({ $0 as? UITableView }).first else {
            XCTFail("Cannot obtain tableView")
            return
        }
        
        XCTAssert(tableView.numberOfSections == 1)
        XCTAssert(tableView.numberOfRows(inSection: 0) == 2) // GlucoseUnit.allCases.count
        
        // when
        sut.tableView(tableView, didSelectRowAt: IndexPath(row: 1, section: 0))
        // then
        XCTAssert(User.current.settings.unit == .mmolL)
        
        // when
        sut.tableView(tableView, didSelectRowAt: IndexPath(row: 0, section: 0))
        // then
        XCTAssert(User.current.settings.unit == .mgDl)
    }
}
