//
//  SettingsChartRangesInteractor.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsChartRangesBusinessLogic {
    func doLoad(request: SettingsChartRanges.Load.Request)
}

protocol SettingsChartRangesDataStore: AnyObject {    
}

final class SettingsChartRangesInteractor: SettingsChartRangesBusinessLogic, SettingsChartRangesDataStore {
    var presenter: SettingsChartRangesPresentationLogic?
    var router: SettingsChartRangesRoutingLogic?
    
    // MARK: Do something
    
    func doLoad(request: SettingsChartRanges.Load.Request) {
        let response = SettingsChartRanges.Load.Response()
        presenter?.presentLoad(response: response)
    }
}
