//
//  AddInjectionPresenter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 11.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddInjectionPresentationLogic {
    func presentLoad(response: AddInjection.Load.Response)
}

final class AddInjectionPresenter: AddInjectionPresentationLogic {
    weak var viewController: AddInjectionDisplayLogic?
    
    // MARK: Do something
    
    func presentLoad(response: AddInjection.Load.Response) {
        let viewModel = AddInjection.Load.ViewModel()
        viewController?.displayLoad(viewModel: viewModel)
    }
}
