//
//  SettingsSensorPresenter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsSensorPresentationLogic {
    func presentLoad(response: SettingsSensor.Load.Response)
}

final class SettingsSensorPresenter: SettingsSensorPresentationLogic {
    weak var viewController: SettingsSensorDisplayLogic?
    
    // MARK: Do something
    
    func presentLoad(response: SettingsSensor.Load.Response) {
        let viewModel = SettingsSensor.Load.ViewModel()
        viewController?.displayLoad(viewModel: viewModel)
    }
}
