//
//  NightscoutCloudBackfillInteractor.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NightscoutCloudBackfillBusinessLogic {
    func doLoad(request: NightscoutCloudBackfill.Load.Request)
    func doSend(request: NightscoutCloudBackfill.Send.Request)
}

protocol NightscoutCloudBackfillDataStore: AnyObject {    
}

final class NightscoutCloudBackfillInteractor: NightscoutCloudBackfillBusinessLogic, NightscoutCloudBackfillDataStore {
    var presenter: NightscoutCloudBackfillPresentationLogic?
    var router: NightscoutCloudBackfillRoutingLogic?
    
    private var date = Date()
    
    // MARK: Do something
    
    func doLoad(request: NightscoutCloudBackfill.Load.Request) {
        let response = NightscoutCloudBackfill.Load.Response(dateChangedHandler: handleDateChanged(_:))
        presenter?.presentLoad(response: response)
    }
    
    func doSend(request: NightscoutCloudBackfill.Send.Request) {
        // TO DO: - add API works
        
        router?.presentPopUp()
    }
    
    private func handleDateChanged(_ date: Date) {
        self.date = date
    }
}
