//
//  StatsRootInteractorTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 11.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

final class StatsRootInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: StatsRootInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupStatsRootInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupStatsRootInteractor() {
        sut = StatsRootInteractor()
    }
    
    // MARK: Test doubles
    
    final class StatsRootPresentationLogicSpy: StatsRootPresentationLogic {
        var presentLoadCalled = false
        
        func presentLoad(response: StatsRoot.Load.Response) {
            presentLoadCalled = true
        }
    }
    
    final class StatsRootRoutingLogicSpy: StatsRootRoutingLogic {
        var dismissSelfCalled = false
        
        func dismissSelf() {
            dismissSelfCalled = true
        }
    }
    
    // MARK: Tests
    
    func testDoLoad() {
        // Given
        let spy = StatsRootPresentationLogicSpy()
        sut.presenter = spy
        let request = StatsRoot.Load.Request()
        
        // When
        sut.doLoad(request: request)
        
        // Then
        XCTAssertTrue(spy.presentLoadCalled, "doLoad(request:) should ask the presenter to format the result")
    }
    
    func testDoCancel() {
        // Given
        let spy = StatsRootRoutingLogicSpy()
        sut.router = spy
        let request = StatsRoot.Cancel.Request()
        
        // When
        sut.doCancel(request: request)
        
        // Then
        XCTAssertTrue(spy.dismissSelfCalled)
    }
}
