//
//  HistoryRootViewControllerTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 11.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

final class HistoryRootViewControllerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: HistoryRootViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupHistoryRootViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupHistoryRootViewController() {
        sut = UIStoryboard(board: .history).instantiate(HistoryRootViewController.self)
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    final class HistoryRootBusinessLogicSpy: HistoryRootBusinessLogic {
        var doLoadCalled = false
        var cancelCalled = false
        
        func doLoad(request: HistoryRoot.Load.Request) {
            doLoadCalled = true
        }
        
        func doCancel(request: HistoryRoot.Cancel.Request) {
            cancelCalled = true
        }
    }
    
    // MARK: Tests
    
    func testShouldDoLoadWhenViewIsLoaded() {
        // Given
        let spy = HistoryRootBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        
        // Then
        XCTAssertTrue(spy.doLoadCalled, "viewDidLoad() should ask the interactor to do load")
    }
    
    func testDisplayLoad() {
        // Given
        let viewModel = HistoryRoot.Load.ViewModel()
        
        // When
        loadView()
        sut.displayLoad(viewModel: viewModel)
        
        // Then
    }
    
    func testCancelHandler() {
        // Given
        let spy = HistoryRootBusinessLogicSpy()
        sut.interactor = spy
        
        let target = sut.navigationItem.leftBarButtonItem!.target!
        let action = sut.navigationItem.leftBarButtonItem!.action!
        
        // When
        _ = target.perform(action)
        
        // Given
        XCTAssertTrue(spy.cancelCalled)
    }
}
