//
//  EditTrainingRouter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 17.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EditTrainingRoutingLogic {
    
}

protocol EditTrainingDataPassing {
    var dataStore: EditTrainingDataStore? { get }
}

final class EditTrainingRouter: NSObject, EditTrainingRoutingLogic, EditTrainingDataPassing {
    weak var viewController: EditTrainingViewController?
    var dataStore: EditTrainingDataStore?
    
    // MARK: Routing
    
}
