//
//  SettingsAlertRootInteractorTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

final class SettingsAlertRootInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: SettingsAlertRootInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupSettingsAlertRootInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSettingsAlertRootInteractor() {
        sut = SettingsAlertRootInteractor()
    }
    
    // MARK: Test doubles
    
    final class SettingsAlertRootPresentationLogicSpy: SettingsAlertRootPresentationLogic {
        var presentLoadCalled = false
        
        func presentLoad(response: SettingsAlertRoot.Load.Response) {
            presentLoadCalled = true
        }
        
        func presentUpdate(response: SettingsAlertRoot.Load.Response) {
            
        }
    }
    
    final class SettingsAlertRootRoutingLogicSpy: SettingsAlertRootRoutingLogic {
        func routeToAlertTypes() {
            
        }
    }
    
    // MARK: Tests
    
    func testDoLoad() {
        // Given
        let spy = SettingsAlertRootPresentationLogicSpy()
        sut.presenter = spy
        let request = SettingsAlertRoot.Load.Request(animated: false)
        
        // When
        sut.doLoad(request: request)
        
        // Then
        XCTAssertTrue(spy.presentLoadCalled, "doLoad(request:) should ask the presenter to format the result")
    }
}
