//
//  SettingsAlertSingleTypeInteractorTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

final class SettingsAlertSingleTypeInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: SettingsAlertSingleTypeInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupSettingsAlertSingleTypeInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSettingsAlertSingleTypeInteractor() {
        sut = SettingsAlertSingleTypeInteractor()
    }
    
    // MARK: Test doubles
    
    final class SettingsAlertSingleTypePresentationLogicSpy: SettingsAlertSingleTypePresentationLogic {
        var presentLoadCalled = false
        
        func presentLoad(response: SettingsAlertSingleType.Load.Response) {
            presentLoadCalled = true
        }
        
        func presentUpdate(response: SettingsAlertSingleType.Load.Response) {
            
        }
    }
    
    final class SettingsAlertSingleTypeRoutingLogicSpy: SettingsAlertSingleTypeRoutingLogic {
        func routeToSound() {
            
        }
    }
    
    // MARK: Tests
    
    func testDoLoad() {
        // Given
        let spy = SettingsAlertSingleTypePresentationLogicSpy()
        sut.presenter = spy
        let request = SettingsAlertSingleType.Load.Request(eventType: .default)
        
        // When
        sut.doLoad(request: request)
        
        // Then
        XCTAssertTrue(spy.presentLoadCalled, "doLoad(request:) should ask the presenter to format the result")
    }
}
