//
//  InitialSetupModels.swift
//  xDrip
//
//  Created by Artem Kalmykov on 28.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum InitialSetup {
    // MARK: Models
    
    enum GenericStep {
        case warning
        case intro
        case deviceMode
        case injectionType
        case settings
        case transmitterType
        case nightscoutSync
        case finish
    }
    
    // MARK: Use cases
    
    enum Load {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum WarningAgreed {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum BeginSetup {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum SkipSetup {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum SelectDeviceMode {
        struct Request {
            let deviceMode: UserDeviceMode
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum SelectInjectionType {
        struct Request {
            let injectionType: UserInjectionType
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum SaveSettings {
        struct Request {
            let alertsEnabled: Bool
            let units: GlucoseUnit
            let nightscoutEnabled: Bool
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum SaveNightscoutCredentials {
        struct Request {
        }
    }
    
    enum SelectDevice {
        struct Request {
            let deviceType: CGMDeviceType
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum FinishSetup {
        struct Request {
        }
    }
    
    enum CompleteCustomDeviceStep {
        struct Request {
            let moreStepsExpected: Bool
            let step: InitialSetupStep
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
}
