//
//  SettingsUnitsPresenter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsUnitsPresentationLogic {
    func presentLoad(response: SettingsUnits.Load.Response)
}

final class SettingsUnitsPresenter: SettingsUnitsPresentationLogic {
    weak var viewController: SettingsUnitsDisplayLogic?
    
    // MARK: Do something
    
    func presentLoad(response: SettingsUnits.Load.Response) {
        let tableViewModel = BaseSettings.ViewModel(sections: [
            createUnitsSection(response: response)
        ])
        
        let viewModel = SettingsUnits.Load.ViewModel(tableViewModel: tableViewModel)
        viewController?.displayLoad(viewModel: viewModel)
    }
    
    private func createUnitsSection(response: SettingsUnits.Load.Response) -> BaseSettings.Section {
        var cells = [BaseSettings.Cell]()
        
        GlucoseUnit.allCases.forEach { (unit) in
            cells.append(createCheckmarkCell(unit, selected: unit == response.currentSelectedUnit, selectionHandler: response.selectionHandler))
        }
        
        return BaseSettings.Section.normal(cells: cells, header: nil, footer: nil)
    }
    
    private func createCheckmarkCell(
        _ unit: GlucoseUnit,
        selected: Bool,
        selectionHandler: @escaping (GlucoseUnit) -> Void) -> BaseSettings.Cell {
        return BaseSettings.Cell.checkmark(mainText: unit.title, selected: selected) {
            selectionHandler(unit)
        }
    }
}

private extension GlucoseUnit {
    var title: String {
        switch self {
        case .mgDl: return "mgDl"
        case .mmolL: return "mmolL"
        }
    }
}
