//
//  SettingsModeMasterRouter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SettingsModeMasterRoutingLogic {
    
}

protocol SettingsModeMasterDataPassing {
    var dataStore: SettingsModeMasterDataStore? { get }
}

final class SettingsModeMasterRouter: NSObject, SettingsModeMasterRoutingLogic, SettingsModeMasterDataPassing {
    weak var viewController: SettingsModeMasterViewController?
    var dataStore: SettingsModeMasterDataStore?
    
    // MARK: Routing
    
}
