//
//  SettingsChartPresenter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 07.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsChartPresentationLogic {
    func presentLoad(response: SettingsChart.Load.Response)
}

final class SettingsChartPresenter: SettingsChartPresentationLogic {
    weak var viewController: SettingsChartDisplayLogic?
    
    // MARK: Do something
    
    func presentLoad(response: SettingsChart.Load.Response) {
        let viewModel = SettingsChart.Load.ViewModel(tableViewModel: [])
        viewController?.displayLoad(viewModel: viewModel)
    }
}
