//
//  SettingsModeRootRouter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsModeRootRoutingLogic {
    func presentSwitchingFromAuthorizedFollower(callback: @escaping (Bool) -> Void)
}

protocol SettingsModeRootDataPassing {
    var dataStore: SettingsModeRootDataStore? { get }
}

final class SettingsModeRootRouter: SettingsModeRootRoutingLogic, SettingsModeRootDataPassing, AlertPresentable {
    weak var viewController: SettingsModeRootViewController?
    weak var dataStore: SettingsModeRootDataStore?
    
    // MARK: Routing
    
    func presentSwitchingFromAuthorizedFollower(callback: @escaping (Bool) -> Void) {
        presentConfirmation(prefix: "settings_mode_switch_from_follower", completion: callback)
    }
}
