//
//  SettingsModeRootInteractor.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsModeRootBusinessLogic {
    func doLoad(request: SettingsModeRoot.Load.Request)
}

protocol SettingsModeRootDataStore {
    
}

final class SettingsModeRootInteractor: SettingsModeRootBusinessLogic, SettingsModeRootDataStore {
    var presenter: SettingsModeRootPresentationLogic?
    var router: SettingsModeRootRoutingLogic?
    
    // MARK: Do something
    
    func doLoad(request: SettingsModeRoot.Load.Request) {
        let response = SettingsModeRoot.Load.Response()
        presenter?.presentLoad(response: response)
    }
}
