//
//  SettingsModeRootModels.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SettingsModeRoot {
    // MARK: Models
    
    // MARK: Use cases
    
    enum Load {
        struct Request {
        }
        
        struct Response {
            let mode: UserDeviceMode
        }
        
        struct ViewModel {
            let mode: UserDeviceMode
        }
    }
    
    enum ChangeMode {
        struct Request {
            let mode: UserDeviceMode
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
}
