//
//  RootPresenterTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 23.02.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

final class RootPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: RootPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupRootPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupRootPresenter() {
        sut = RootPresenter()
    }
    
    // MARK: Test doubles
    
    final class RootDisplayLogicSpy: RootDisplayLogic {
        var displayLoadCalled = false
        var displayAddEntryCalled = false
        
        func displayLoad(viewModel: Root.Load.ViewModel) {
            displayLoadCalled = true
        }
        
        func displayAddEntry(viewModel: Root.ShowAddEntryOptionsList.ViewModel) {
            displayAddEntryCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentLoad() {
        // Given
        let spy = RootDisplayLogicSpy()
        sut.viewController = spy
        let response = Root.Load.Response()
        
        // When
        sut.presentLoad(response: response)
        
        // Then
        XCTAssertTrue(
            spy.displayLoadCalled,
            "presentLoad(response:) should ask the view controller to display the result"
        )
    }
    
    func testPresentAddEntry() {
        // Given
        let spy = RootDisplayLogicSpy()
        sut.viewController = spy
        
        let response = Root.ShowAddEntryOptionsList.Response(types: [])
        
        // When
        sut.presentAddEntry(response: response)
        
        // Then
        XCTAssertTrue(
            spy.displayAddEntryCalled,
            "presentLoad(response:) should ask the view controller to display the result"
        )
    }
}
