//
//  HistoryRootInteractor.swift
//  xDrip
//
//  Created by Artem Kalmykov on 11.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift

protocol HistoryRootBusinessLogic {
    func doLoad(request: HistoryRoot.Load.Request)
    func doCancel(request: HistoryRoot.Cancel.Request)
    func doChangeChartTimeFrame(request: HistoryRoot.ChangeEntriesChartTimeFrame.Request)
    func doChangeChartDate(request: HistoryRoot.ChangeEntriesChartDate.Request)
}

protocol HistoryRootDataStore: AnyObject {
}

final class HistoryRootInteractor: HistoryRootBusinessLogic, HistoryRootDataStore {
    var presenter: HistoryRootPresentationLogic?
    var router: HistoryRootRoutingLogic?
    
    private let glucoseDataWorker: HomeGlucoseDataWorkerProtocol
    private let lightGlucoseDataWorker: HistoryGlucoseDataWorkerProtocol
    private var timeline: HistoryRoot.Timeline = .last14Days
    private var selectedDate = Date()
    
    private var chartDate: Date? {
        return timeline == .last14Days ? nil : selectedDate
    }
    
    private var interval: TimeInterval {
        return timeline == .last14Days ? TimeInterval(hours: 14.0 * 24.0) : .secondsPerDay
    }
    
    init() {
        glucoseDataWorker = HomeGlucoseDataWorker()
        lightGlucoseDataWorker = HistoryGlucoseDataWorker()
    }
    
    // MARK: Do something
    
    func doLoad(request: HistoryRoot.Load.Request) {
        let response = HistoryRoot.Load.Response(globalTimeInterval: interval)
        presenter?.presentLoad(response: response)
        updateGlucoseChartData()
    }
    
    func doCancel(request: HistoryRoot.Cancel.Request) {
        router?.dismissSelf()
    }
    
    func doChangeChartTimeFrame(request: HistoryRoot.ChangeEntriesChartTimeFrame.Request) {
        timeline = request.timeline
        let response = HistoryRoot.ChangeEntriesChartTimeFrame.Response(timeInterval: interval)
        presenter?.presentChartTimeFrameChange(response: response)
        updateGlucoseChartData()
    }
    
    func doChangeChartDate(request: HistoryRoot.ChangeEntriesChartDate.Request) {
        selectedDate = request.date
        
        updateGlucoseChartData()
    }
    
    // MARK: Logic
    
    private func updateGlucoseChartData() {
        var glucoseData = [BaseGlucoseReading]()
        let basalData = BasalChartDataWorker.fetchAllBasalDataForCurrentMode()
        
        let lightReadings = LightGlucoseReading.allForCurrentMode
        let grossReadings = GlucoseReading.allForCurrentMode()
        
        if timeline == .last14Days {
            let lightGlucoseData = lightGlucoseDataWorker.fetchGlucoseData(for: 14 * 24, readings: lightReadings)
            let grossGlucoseData = glucoseDataWorker.fetchGlucoseData(for: 14 * 24, readings: grossReadings)
            
            glucoseData = grossGlucoseData + lightGlucoseData
        } else {
            let lightGlucoseData = lightGlucoseDataWorker.fetchGlucoseData(for: selectedDate, readings: lightReadings)
            let grossGlucoseData = glucoseDataWorker.fetchGlucoseData(for: selectedDate, readings: grossReadings)
            
            glucoseData = grossGlucoseData + lightGlucoseData
        }
        
        let response = HistoryRoot.GlucoseDataUpdate.Response(
            glucoseData: glucoseData,
            intervalGlucoseData: glucoseData,
            basalDisplayMode: User.current.settings.chart?.basalDisplayMode ?? .notShown,
            basalData: basalData,
            date: chartDate
        )
        presenter?.presentGlucoseData(response: response)
    }
}
