//
//  HistoryRootRouter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 11.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HistoryRootRoutingLogic {
    func dismissSelf()
}

protocol HistoryRootDataPassing {
    var dataStore: HistoryRootDataStore? { get }
}

final class HistoryRootRouter: NSObject, HistoryRootRoutingLogic, HistoryRootDataPassing {
    weak var viewController: HistoryRootViewController?
    var dataStore: HistoryRootDataStore?
    
    // MARK: Routing
    
    func dismissSelf() {
        viewController?.dismiss(animated: true, completion: nil)
    }
}
