//
//  EditCalibrationPresenterTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 17.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

// swiftlint:disable implicitly_unwrapped_optional

final class EditCalibrationPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: EditCalibrationPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupEditCalibrationPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupEditCalibrationPresenter() {
        sut = EditCalibrationPresenter()
    }
    
    // MARK: Test doubles
    
    final class EditCalibrationDisplayLogicSpy: EditCalibrationDisplayLogic {
        var displayUpdateDataCalled = false
        
        func displayUpdateData(viewModel: EditCalibration.UpdateData.ViewModel) {
            displayUpdateDataCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentLoad() {
        // Given
        let spy = EditCalibrationDisplayLogicSpy()
        sut.viewController = spy
        let response = EditCalibration.UpdateData.Response(
            hasInitialCalibrations: false,
            datePickerValueChanged: { _, _ in },
            glucosePickerValueChanged: { _, _ in },
            value1: "",
            value2: "",
            date1: Date(),
            date2: Date()
        )
        
        // When
        sut.presentUpdateData(response: response)
        
        // Then
        XCTAssertTrue(
            spy.displayUpdateDataCalled,
            "presentLoad(response:) should ask the view controller to display the result"
        )
    }
}
