//
//  NightscoutCloudConfigurationInteractorTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

// swiftlint:disable implicitly_unwrapped_optional

final class NightscoutCloudConfigurationInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: NightscoutCloudConfigurationInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupNightscoutCloudConfigurationInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupNightscoutCloudConfigurationInteractor() {
        sut = NightscoutCloudConfigurationInteractor()
    }
    
    // MARK: Test doubles
    
    final class NightscoutCloudConfigurationPresentationLogicSpy: NightscoutCloudConfigurationPresentationLogic {
        var presentLoadCalled = false
        
        func presentLoad(response: NightscoutCloudConfiguration.UpdateData.Response) {
            presentLoadCalled = true
        }
    }
    
    final class NightscoutCloudConfigurationRoutingLogicSpy: NightscoutCloudConfigurationRoutingLogic {
        func routeToExtraOptions() {
        }
    }
    
    // MARK: Tests
    
    func testDoLoad() {
        // Given
        let spy = NightscoutCloudConfigurationPresentationLogicSpy()
        sut.presenter = spy
        let request = NightscoutCloudConfiguration.UpdateData.Request()
        
        // When
        sut.doLoad(request: request)
        
        // Then
        XCTAssertTrue(spy.presentLoadCalled, "doLoad(request:) should ask the presenter to format the result")
    }
}
