//
//  StatsRootRouter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 11.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol StatsRootRoutingLogic {
    func dismissSelf()
}

protocol StatsRootDataPassing {
    var dataStore: StatsRootDataStore? { get }
}

final class StatsRootRouter: NSObject, StatsRootRoutingLogic, StatsRootDataPassing {
    weak var viewController: StatsRootViewController?
    var dataStore: StatsRootDataStore?
    
    // MARK: Routing
    
    func dismissSelf() {
        viewController?.dismiss(animated: true, completion: nil)
    }
}
