//
//  SettingsAlertSoundPresenterTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

final class SettingsAlertSoundPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: SettingsAlertSoundPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupSettingsAlertSoundPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSettingsAlertSoundPresenter() {
        sut = SettingsAlertSoundPresenter()
    }
    
    // MARK: Test doubles
    
    final class SettingsAlertSoundDisplayLogicSpy: SettingsAlertSoundDisplayLogic {
        var displayLoadCalled = false
        
        func displayLoad(viewModel: SettingsAlertSound.Load.ViewModel) {
            displayLoadCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentLoad() {
        // Given
        let spy = SettingsAlertSoundDisplayLogicSpy()
        sut.viewController = spy
        let response = SettingsAlertSound.Load.Response()
        
        // When
        sut.presentLoad(response: response)
        
        // Then
        XCTAssertTrue(spy.displayLoadCalled, "presentLoad(response:) should ask the view controller to display the result")
    }
}
