//
//  EditCalibrationViewController.swift
//  xDrip
//
//  Created by Artem Kalmykov on 17.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditCalibrationDisplayLogic: AnyObject {
    func displayUpdateData(viewModel: EditCalibration.UpdateData.ViewModel)
}

class EditCalibrationViewController: BaseSettingsViewController, EditCalibrationDisplayLogic {
    var interactor: EditCalibrationBusinessLogic?
    var router: EditCalibrationDataPassing?
    var dismissHandler: (() -> Void)?
    
    // MARK: Object lifecycle
    
    @available(*, unavailable)
    required init?(coder aDecoder: NSCoder) {
        fatalError("Use regular init")
    }
    
    required init() {
        super.init()
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = EditCalibrationInteractor()
        let presenter = EditCalibrationPresenter()
        let router = EditCalibrationRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.router = router
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: IB
    
    @objc private func onSaveButtonTap() {
        let request = EditCalibration.Save.Request()
        interactor?.doSave(request: request)
    }
    
    @objc private func onCancelButtonTap() {
        let request = EditCalibration.Dismiss.Request()
        interactor?.doDismiss(request: request)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doLoad()
        setupUI()
        setupNavigationItems()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        dismissHandler?()
    }
    
    // MARK: Do something
    
    private func doLoad() {
        let request = EditCalibration.UpdateData.Request()
        interactor?.doUpdateData(request: request)
    }
    
    private func setupNavigationItems() {
        let cancelButton = UIBarButtonItem(
            barButtonSystemItem: .cancel,
            target: self,
            action: #selector(onCancelButtonTap)
        )
        navigationItem.leftBarButtonItem = cancelButton
        
        let doneButton = UIBarButtonItem(
            barButtonSystemItem: .done,
            target: self,
            action: #selector(onSaveButtonTap)
        )
        navigationItem.rightBarButtonItem = doneButton
    }
    
    private func setupUI() {
        title = "edit_calibration_scene_title".localized
    }
    
    // MARK: Display
    
    func displayUpdateData(viewModel: EditCalibration.UpdateData.ViewModel) {
        update(with: viewModel.tableViewModel)
    }
}
