//
//  SettingsModeMasterPresenterTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

final class SettingsModeMasterPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: SettingsModeMasterPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupSettingsModeMasterPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSettingsModeMasterPresenter() {
        sut = SettingsModeMasterPresenter()
    }
    
    // MARK: Test doubles
    
    final class SettingsModeMasterDisplayLogicSpy: SettingsModeMasterDisplayLogic {
        var displayLoadCalled = false
        
        func displayLoad(viewModel: SettingsModeMaster.Load.ViewModel) {
            displayLoadCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentLoad() {
        // Given
        let spy = SettingsModeMasterDisplayLogicSpy()
        sut.viewController = spy
        let response = SettingsModeMaster.Load.Response()
        
        // When
        sut.presentLoad(response: response)
        
        // Then
        XCTAssertTrue(spy.displayLoadCalled, "presentLoad(response:) should ask the view controller to display the result")
    }
}
