//
//  EntriesListInteractorTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 17.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

// swiftlint:disable implicitly_unwrapped_optional

final class EntriesListInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: EntriesListInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupEntriesListInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupEntriesListInteractor() {
        sut = EntriesListInteractor(
            persistenceWorker: EntriesListCarbsPersistenceWorker()
        )
    }
    
    // MARK: Test doubles
    
    final class EntriesListPresentationLogicSpy: EntriesListPresentationLogic {
        var presentLoadCalled = false
        
        func presentUpdateData(response: EntriesList.UpdateData.Response) {
            presentLoadCalled = true
        }
    }
    
    final class EntriesListRoutingLogicSpy: EntriesListRoutingLogic {
        var dismissSceneCalled = false
        var routeToEditEntryCalled = false
        
        func dismissScene() {
            dismissSceneCalled = true
        }
        
        func routeToEditEntry() {
            routeToEditEntryCalled = true
        }
    }
    
    // MARK: Tests
    
    func testDoLoad() {
        // Given
        let spy = EntriesListPresentationLogicSpy()
        sut.presenter = spy
        let request = EntriesList.UpdateData.Request()
        
        // When
        sut.doUpdateData(request: request)
        
        // Then
        XCTAssertTrue(spy.presentLoadCalled, "doUpdateData(request:) should ask the presenter to format the result")
    }
    
    func testDoCancel() {
        // Given
        let spy = EntriesListRoutingLogicSpy()
        sut.router = spy
        let request = EntriesList.Cancel.Request()
        
        // When
        sut.doCancel(request: request)
        
        // Then
        XCTAssertTrue(spy.dismissSceneCalled)
    }
    
    func testRouteToEditEntryCalled() {
        CarbEntriesWorker.addCarbEntry(amount: 0.0, foodType: nil, date: Date())
        
        let spy = EntriesListRoutingLogicSpy()
        sut.router = spy
        
        let request = EntriesList.ShowSelectedEntry.Request(index: 0)
        sut.doShowSelectedEntry(request: request)
        
        XCTAssertTrue(spy.routeToEditEntryCalled)
        
        sut.entriesWorker.deleteEntry(0)
    }
}
