//
//  SettingsModeRootViewControllerTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

// swiftlint:disable implicitly_unwrapped_optional

final class SettingsModeRootViewControllerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: SettingsModeRootViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupSettingsModeRootViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSettingsModeRootViewController() {
        sut = SettingsModeRootViewController()
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    final class SettingsModeRootBusinessLogicSpy: SettingsModeRootBusinessLogic {
        var doLoadCalled = false
        var doChangeModeCalled = false
        
        func doLoad(request: SettingsModeRoot.Load.Request) {
            doLoadCalled = true
        }
        
        func doChangeMode(request: SettingsModeRoot.ChangeMode.Request) {
            doChangeModeCalled = true
        }
    }
    
    // MARK: Tests
    
    func testShouldDoLoadWhenViewIsLoaded() {
        // Given
        let spy = SettingsModeRootBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        
        // Then
        XCTAssertTrue(spy.doLoadCalled, "viewDidLoad() should ask the interactor to do load")
    }
    
    func testDisplayLoad() {
        // Given
        let viewModel = SettingsModeRoot.Load.ViewModel(mode: .main)
        
        // When
        loadView()
        sut.displayLoad(viewModel: viewModel)
        
        // Then
    }
    
    func testTabBar() {
        loadView()
        
        guard let tabBar = sut.children.compactMap({ $0 as? UITabBarController }).first else {
            XCTFail("Cannot obtain tabbar")
            return
        }
        
        XCTAssertTrue(tabBar.viewControllers?.count == 2)
        XCTAssertTrue(tabBar.viewControllers?[0] is  SettingsModeMasterViewController)
        XCTAssertTrue(tabBar.viewControllers?[1] is SettingsModeFollowerViewController)
        
        guard let segmentedControl = sut.view.subviews.compactMap({ $0 as? UISegmentedControl }).first else {
            XCTFail("Cannot obtain segmented control")
            return
        }
        
        let settings = User.current.settings
        
        XCTAssertTrue(segmentedControl.numberOfSegments == 2)
        
        // When
        segmentedControl.selectedSegmentIndex = 0
        segmentedControl.sendActions(for: .valueChanged)
        // Then
        XCTAssertTrue(tabBar.selectedIndex == 0)
        XCTAssertTrue(settings?.deviceMode == .main)
        
        // When
        segmentedControl.selectedSegmentIndex = 1
        segmentedControl.sendActions(for: .valueChanged)
        // Then
        XCTAssertTrue(tabBar.selectedIndex == 1)
        XCTAssertTrue(settings?.deviceMode == .follower)
    }
    
    func testDoChangeModeShouldCall() {
        let spy = SettingsModeRootBusinessLogicSpy()
        sut.interactor = spy
        loadView()
        
        guard let segmentedControl = sut.view.subviews.compactMap({ $0 as? UISegmentedControl }).first else {
            XCTFail("Cannot obtain segmented control")
            return
        }
        
        // When
        segmentedControl.selectedSegmentIndex = 0
        segmentedControl.sendActions(for: .valueChanged)
        
        XCTAssertTrue(spy.doChangeModeCalled)
    }
}
