//
//  SettingsCloudTypesInteractorTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

// swiftlint:disable implicitly_unwrapped_optional

final class SettingsCloudTypesInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: SettingsCloudTypesInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupSettingsCloudTypesInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSettingsCloudTypesInteractor() {
        sut = SettingsCloudTypesInteractor()
    }
    
    // MARK: Test doubles
    
    final class SettingsCloudTypesPresentationLogicSpy: SettingsCloudTypesPresentationLogic {
        var presentLoadCalled = false
        
        func presentLoad(response: SettingsCloudTypes.Load.Response) {
            presentLoadCalled = true
        }
    }
    
    final class SettingsCloudTypesRoutingLogicSpy: SettingsCloudTypesRoutingLogic {
        func routeToNightscoutCloudConfiguration() {
        }
    }
    
    // MARK: Tests
    
    func testDoLoad() {
        // Given
        let spy = SettingsCloudTypesPresentationLogicSpy()
        sut.presenter = spy
        let request = SettingsCloudTypes.Load.Request()
        
        // When
        sut.doLoad(request: request)
        
        // Then
        XCTAssertTrue(spy.presentLoadCalled, "doLoad(request:) should ask the presenter to format the result")
    }
}
