//
//  SettingsTransmitterInteractor.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsTransmitterBusinessLogic {
    func doLoad(request: SettingsTransmitter.Load.Request)
}

protocol SettingsTransmitterDataStore: AnyObject {    
}

final class SettingsTransmitterInteractor: SettingsTransmitterBusinessLogic, SettingsTransmitterDataStore {
    var presenter: SettingsTransmitterPresentationLogic?
    var router: SettingsTransmitterRoutingLogic?
    
    // MARK: Do something
    
    func doLoad(request: SettingsTransmitter.Load.Request) {
        let response = SettingsTransmitter.Load.Response()
        presenter?.presentLoad(response: response)
    }
}
