//
//  SettingsUserTypeRootInteractorTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

final class SettingsUserTypeRootInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: SettingsUserTypeRootInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupSettingsUserTypeRootInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSettingsUserTypeRootInteractor() {
        sut = SettingsUserTypeRootInteractor()
    }
    
    // MARK: Test doubles
    
    final class SettingsUserTypeRootPresentationLogicSpy: SettingsUserTypeRootPresentationLogic {
        var presentLoadCalled = false
        
        func presentLoad(response: SettingsUserTypeRoot.Load.Response) {
            presentLoadCalled = true
        }
    }
    
    final class SettingsUserTypeRootRoutingLogicSpy: SettingsUserTypeRootRoutingLogic {
        
    }
    
    // MARK: Tests
    
    func testDoLoad() {
        // Given
        let spy = SettingsUserTypeRootPresentationLogicSpy()
        sut.presenter = spy
        let request = SettingsUserTypeRoot.Load.Request()
        
        // When
        sut.doLoad(request: request)
        
        // Then
        XCTAssertTrue(spy.presentLoadCalled, "doLoad(request:) should ask the presenter to format the result")
    }
}
