//
//  SettingsChartRangesInteractorTests.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import xDrip
import XCTest

final class SettingsChartRangesInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: SettingsChartRangesInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupSettingsChartRangesInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSettingsChartRangesInteractor() {
        sut = SettingsChartRangesInteractor()
    }
    
    // MARK: Test doubles
    
    final class SettingsChartRangesPresentationLogicSpy: SettingsChartRangesPresentationLogic {
        var presentLoadCalled = false
        
        func presentLoad(response: SettingsChartRanges.Load.Response) {
            presentLoadCalled = true
        }
    }
    
    final class SettingsChartRangesRoutingLogicSpy: SettingsChartRangesRoutingLogic {
        
    }
    
    // MARK: Tests
    
    func testDoLoad() {
        // Given
        let spy = SettingsChartRangesPresentationLogicSpy()
        sut.presenter = spy
        let request = SettingsChartRanges.Load.Request()
        
        // When
        sut.doLoad(request: request)
        
        // Then
        XCTAssertTrue(spy.presentLoadCalled, "doLoad(request:) should ask the presenter to format the result")
    }
}
