//
//  SettingsPumpUserRouter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 09.04.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SettingsPumpUserRoutingLogic {
    
}

protocol SettingsPumpUserDataPassing {
    var dataStore: SettingsPumpUserDataStore? { get }
}

final class SettingsPumpUserRouter: NSObject, SettingsPumpUserRoutingLogic, SettingsPumpUserDataPassing {
    weak var viewController: SettingsPumpUserViewController?
    var dataStore: SettingsPumpUserDataStore?
    
    // MARK: Routing
    
}
