//
//  HomeRouter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 11.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeToCarbsEntriesList()
    func routeToBolusEntriesList()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

final class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: Routing
    
    func routeToBolusEntriesList() {
        routeToEntriesList(for: .bolus)
    }
    
    func routeToCarbsEntriesList() {
        routeToEntriesList(for: .carbs)
    }
    
    private func routeToEntriesList(for type: Root.EntryType) {
        let builder = EntriesListSceneBuilder()
        let viewController: UIViewController?
        switch type {
        case .carbs:
            viewController = builder.createSceneForCarbs()
        case .bolus:
            viewController = builder.createSceneForBolus()
        default:
            viewController = nil
        }
        
        guard let controller = viewController else { return }
        self.viewController?.present(controller.embedInNavigation(), animated: true)
    }
}
