//
//  EntriesListRouter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 17.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol EntriesListRoutingLogic {
    func dismissScene()
}

protocol EntriesListDataPassing {
    var dataStore: EntriesListDataStore? { get }
}

final class EntriesListRouter: NSObject, EntriesListRoutingLogic, EntriesListDataPassing {
    weak var viewController: EntriesListViewController?
    var dataStore: EntriesListDataStore?
    
    static let entriesListNavigationControllerIdentifier = "EntriesListNavigationController"
    
    // MARK: Routing
    
    func dismissScene() {
        viewController?.dismiss(animated: true, completion: nil)
    }
}
