//
//  EntriesListPresenter.swift
//  xDrip
//
//  Created by Artem Kalmykov on 17.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EntriesListPresentationLogic {
    func presentLoad(response: EntriesList.Load.Response)
}

final class EntriesListPresenter: EntriesListPresentationLogic {
    weak var viewController: EntriesListDisplayLogic?
    let formattingWorker: EntriesListFormattingWorker
    
    init(formattingWorker: EntriesListFormattingWorker) {
        self.formattingWorker = formattingWorker
    }
    
    // MARK: Do something
    
    func presentLoad(response: EntriesList.Load.Response) {
        let entries = response.entries
        let cellViewModel = formattingWorker.formatEntries(entries)
        
        let title = "entries_list_data_section_title".localized
        
        let viewModel = EntriesList.Load.ViewModel(items: [EntriesList.SectionViewModel(title: title, items: cellViewModel)])
        viewController?.displayLoad(viewModel: viewModel)
    }
}
