//
//  EditFoodEntryModels.swift
//  xDrip
//
//  Created by Artem Kalmykov on 17.03.2020.
//  Copyright (c) 2020 Faifly. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum EditFoodEntry {
    // MARK: Models
    
    enum Field {
        case carbsAmount
        case carbsDate
        case foodType
        case insulinAmount
        case insulinDate
    }
    
    enum EntryType {
        case food
        case bolus
        case basal
        case carbs
    }
    
    enum Mode {
        case create
        case edit
    }
    
    // MARK: Use cases
    
    enum Load {
        struct Request {
        }
        
        struct Response {
            let insulinEntry: InsulinEntry?
            let carbEntry: CarbEntry?
            let entryType: EntryType
            let textChangedHandler: (Field, String?) -> Void
            let dateChangedHandler: (Field, Date) -> Void
            let foodTypeChangedHandler: (String?) -> Void
        }
        
        struct ViewModel {
            let tableViewModel: BaseSettings.ViewModel
        }
    }
    
    enum Cancel {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
    enum Save {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
